Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	vcf_gds
	1

[Wed Mar  6 14:44:54 2019]
rule vcf_gds:
    input: /home/kgoldmann/Documents/PEAC_eqtl/Outputs/DNA/PEAC_chr22_sub.vcf.gz, /home/kgoldmann/Documents/PEAC_eqtl/Outputs/DNA/RP_chr22_sub.vcf.gz
    output: /home/kgoldmann/Documents/PEAC_eqtl/Outputs/DNA/PEAC_PCA.gds, /home/kgoldmann/Documents/PEAC_eqtl/Outputs/DNA/RP_PCA.gds
    jobid: 0

[Wed Mar  6 14:44:57 2019]
Error in rule vcf_gds:
    jobid: 0
    output: /home/kgoldmann/Documents/PEAC_eqtl/Outputs/DNA/PEAC_PCA.gds, /home/kgoldmann/Documents/PEAC_eqtl/Outputs/DNA/RP_PCA.gds

RuleException:
CalledProcessError in line 295 of /home/kgoldmann/Documents/Git/peac/Snakefile:
Command ' set -euo pipefail;  Rscript --vanilla /home/kgoldmann/Documents/Git/peac/.snakemake/scripts/tmp10wrx9ng.vcf_PCA2gds.R ' returned non-zero exit status 1.
  File "/home/kgoldmann/Documents/Git/peac/Snakefile", line 295, in __rule_vcf_gds
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job vcf_gds since they might be corrupted:
/home/kgoldmann/Documents/PEAC_eqtl/Outputs/DNA/PEAC_PCA.gds, /home/kgoldmann/Documents/PEAC_eqtl/Outputs/DNA/RP_PCA.gds
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/kgoldmann/Documents/Git/peac/.snakemake/log/2019-03-06T144454.537748.snakemake.log
